- name: Enable and start beanstalkd
  service:
    name: beanstalkd
    state: started
    enabled: yes
  tags:
    - always

- name: Start workers
  shell: |
    source virtualenv/bin/activate
    {% if libcloud_ssl_cert_file %}
    export SSL_CERT_FILE={{ libcloud_ssl_cert_file }}
    {% endif %}
    bash docs/_static/worker_start.sh {{ machine_type }} {{ workers }}
  args:
    chdir: /home/{{ teuthology_execution_user }}/src/teuthology_master
  become_user: "{{ teuthology_execution_user }}"

- name: Tweak ssh_config
  blockinfile:
    create: yes
    block: |
      Host *
        StrictHostKeyChecking no
        UserKnownHostsFile=/dev/null

    path: "/home/{{ teuthology_execution_user }}/.ssh/config"
  become_user: "{{ teuthology_execution_user }}"
